version: '3.8'
services:
  redis:
    container_name: "bjredisdev"
    restart: unless-stopped
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - redisdev:/data
  database:
    container_name: "bjdbdev"
    restart: unless-stopped
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "nest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - bjdbdev:/var/lib/postgresql/data
volumes:
  redisdev:
  bjdbdev: