version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    image: bjbackend:latest
    container_name: "bjbackend"
    restart: unless-stopped
    build: ../../backend/
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SUBMISSIONS_PATH_HOST}:${SUBMISSIONS_PATH}
    depends_on:
      - database
      - redis
  redis:
    container_name: "bjredis"
    restart: unless-stopped
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  database:
    container_name: "bjdb"
    restart: unless-stopped
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - bjdb:/var/lib/postgresql/data
    env_file:
      - ../../backend/.env.prod

volumes:
  redis:
  bjdb: