version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: "webserver"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  backend:
    image: bjbackend:latest
    container_name: "bjbackend"
    restart: unless-stopped
    build: ../../backend/
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SUBMISSIONS_PATH_HOST}:${SUBMISSIONS_PATH}
    depends_on:
      - database
      - redis
  frontend:
    image: bjfrontend:latest
    container_name: "bjfrontend"
    restart: unless-stopped
    build: ../../frontend/
    ports:
      - 127.0.0.1:8080:8080
  redis:
    container_name: "bjredis"
    restart: unless-stopped
    image: 'redis:alpine'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis:/data
  database:
    container_name: "bjdb"
    restart: unless-stopped
    image: postgres:13
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - bjdb:/var/lib/postgresql/data
    env_file:
      - ../../backend/.env.prod
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  redis:
  bjdb: